include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - unnecessary_new
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
    - avoid_print
